export { OutboundClient } from './client';

// Error classes
export {
  OutboundError,
  BadRequestError,
  AuthenticationError,
  ForbiddenError,
  NotFoundError,
  ConflictError,
  RateLimitError,
  ServerError,
  TimeoutError,
  NetworkError,
} from './errors';

// All types
export type {
  OutboundConfig,
  ResolvedConfig,
  SendEmailParams,
  Attachment,
  SendEmailResponse,
  BulkEmailParams,
  BulkEmailRecipient,
  BulkEmailResponse,
  JobStatusResponse,
  EmailRecipientStatus,
  EmailStatus,
  CreateTemplateParams,
  UpdateTemplateParams,
  ListTemplatesParams,
  ListTemplatesResponse,
  Template,
  TemplateResponse,
  TemplateSendParams,
  TemplateBulkSendParams,
  TemplateBulkRecipient,
  TemplateBulkSendResponse,
  TemplatePreviewParams,
  TemplatePreviewResponse,
  TemplateStatsResponse,
  ListSuppressionsParams,
  ListSuppressionsResponse,
  Suppression,
  AddSuppressionParams,
  SuppressionResponse,
  WebhookEvent,
  CreateWebhookParams,
  UpdateWebhookParams,
  Webhook,
  CreateWebhookResponse,
  UpdateWebhookResponse,
  ListWebhooksResponse,
  DashboardResponse,
  QuotaResponse,
} from './types';
